# ===============================
# Application
# ===============================
spring.application.name=dsa
server.port=${PORT:8083}
server.address=0.0.0.0

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=VARCHAR
spring.rabbitmq.host=localhost
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

# ===============================
# Redis Configuration
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT:6379}
# If using a password or custom cluster via environment variables:
# spring.data.redis.password=${REDIS_PASSWORD}
# ===============================
# Frontend / Upload
# ===============================
app.frontend-url=${FRONTEND_URL}
app.upload.dir=uploads

# ===============================
# Multipart File Upload
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ===============================
# Timezone
# ===============================
spring.jackson.time-zone=Asia/Dhaka
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Dhaka

# ===============================
# Logging
# ===============================
logging.level.com.cuet.dsa=DEBUG
logging.level.org.springframework.security=WARN
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.amqp.rabbit.listener=DEBUG
logging.level.org.springframework.amqp.rabbit.annotation=DEBUG

app.jwt.secret=${SECRET_KEY}
app.jwt.access-expiration=${ACCESS_EXPIRATION}
app.jwt.refresh-expiration=${REFRESH_EXPIRATION}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.jpa.hibernate.ddl-auto=update
